
CREATE TABLE CADASTRO (
                CODIGO INTEGER NOT NULL,
                SENHA VARCHAR(8) NOT NULL,
                NOME VARCHAR(20) NOT NULL,
                SOBRENOME VARCHAR(20) NOT NULL,
                EMAIL VARCHAR(50) NOT NULL,
                CONSTRAINT ID PRIMARY KEY (CODIGO)
);


CREATE TABLE ENTRADA (
                CODIGO INTEGER NOT NULL,
                NOME VARCHAR(20) NOT NULL,
                SENHA VARCHAR(8) NOT NULL,
                CONSTRAINT ID1 PRIMARY KEY (CODIGO)
);


ALTER TABLE ENTRADA ADD CONSTRAINT CADASTRO_ENTRADA_fk
FOREIGN KEY (CODIGO)
REFERENCES CADASTRO (CODIGO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
