
CREATE TABLE CLIENTE (
                CPF DECIMAL(11) NOT NULL,
                EMAIL VARCHAR(60) NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                TELEFONE VARCHAR(20) NOT NULL,
                CONSTRAINT CPF PRIMARY KEY (CPF)
);


CREATE TABLE ENDERECO (
                CPF DECIMAL(11) NOT NULL,
                LOGRADOURO VARCHAR(60) NOT NULL,
                CEP VARCHAR NOT NULL,
                BAIRRO VARCHAR(40) NOT NULL,
                CIDADE VARCHAR(40) NOT NULL,
                ESTADO VARCHAR(2) NOT NULL,
                CONSTRAINT CODIGO_ENDERECO PRIMARY KEY (CPF)
);


CREATE TABLE PRODUTO (
                CODIGO INTEGER NOT NULL,
                CPF_cliente DECIMAL(11) NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                DESCRICAO VARCHAR(60) NOT NULL,
                PRECO_UNITARIO DECIMAL(4) NOT NULL,
                QUANTIDADE NUMERIC(10) NOT NULL,
                CONSTRAINT CODIGO_PRODUTO PRIMARY KEY (CODIGO, CPF_cliente)
);


CREATE TABLE DETALHES_TRANSACAO (
                CODIGO INTEGER NOT NULL,
                CPF_cliente DECIMAL(11) NOT NULL,
                NUMERO_PEDIDO NUMERIC NOT NULL,
                DATA DATE NOT NULL,
                HORARIO TIME NOT NULL,
                METODO_PAGAMENTO VARCHAR(50) NOT NULL,
                CONSTRAINT CODIGO_TRANSACAO PRIMARY KEY (CODIGO, CPF_cliente)
);


CREATE TABLE PAGAMENTO (
                CODIGO INTEGER NOT NULL,
                CPF_cliente DECIMAL(11) NOT NULL,
                NUMERO_CARTAO NUMERIC(20) NOT NULL,
                CVV NUMERIC(3) NOT NULL,
                DATA_VALIDADE DATE NOT NULL,
                CONSTRAINT CODIGO_PAGAMENTO PRIMARY KEY (CODIGO, CPF_cliente)
);


CREATE TABLE ENVIO (
                CODIGO_PRODUTO INTEGER NOT NULL,
                CPF_cliente DECIMAL(11) NOT NULL,
                METODO VARCHAR(50) NOT NULL,
                RASTREAMENTO NUMERIC NOT NULL,
                CONSTRAINT CODIGO_ENVIO PRIMARY KEY (CODIGO_PRODUTO, CPF_cliente)
);


ALTER TABLE PRODUTO ADD CONSTRAINT CLIENTE_PRODUTO_fk
FOREIGN KEY (CPF_cliente)
REFERENCES CLIENTE (CPF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE ENDERECO ADD CONSTRAINT CLIENTE_ENDERECO_fk
FOREIGN KEY (CPF)
REFERENCES CLIENTE (CPF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE ENVIO ADD CONSTRAINT PRODUTO_ENVIO_fk
FOREIGN KEY (CODIGO_PRODUTO, CPF_cliente)
REFERENCES PRODUTO (CODIGO, CPF_cliente)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE DETALHES_TRANSACAO ADD CONSTRAINT PRODUTO_DETALHES_TRANSACAO_fk
FOREIGN KEY (CODIGO, CPF_cliente)
REFERENCES PRODUTO (CODIGO, CPF_cliente)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE PAGAMENTO ADD CONSTRAINT DETALHES_TRANSACAO_PAGAMENTO_fk
FOREIGN KEY (CODIGO, CPF_cliente)
REFERENCES DETALHES_TRANSACAO (CODIGO, CPF_cliente)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
